version: '3.9'

services:
  orchestrator:
    container_name: orchestrator
    build:
      context: ./agent_orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./agent_orchestrator:/app
    depends_on:
      - agent_service
      - kafka
    networks:
      - agentic-net

  agent_service:
    container_name: agent_service
    build:
      context: ./agent_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./agent_service:/app
    depends_on:
      - kafka
    networks:
      - agentic-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - agentic-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - agentic-net

networks:
  agentic-net:
    driver: bridge
