# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/agent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/agent.proto\x12\x05\x61gent\"/\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"+\n\tTaskReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t2?\n\x0c\x41gentService\x12/\n\x07RunTask\x12\x12.agent.TaskRequest\x1a\x10.agent.TaskReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.agent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKREQUEST._serialized_start=28
  _TASKREQUEST._serialized_end=75
  _TASKREPLY._serialized_start=77
  _TASKREPLY._serialized_end=120
  _AGENTSERVICE._serialized_start=122
  _AGENTSERVICE._serialized_end=185
# @@protoc_insertion_point(module_scope)